### ISSUE TITLE
The network address 'http://akswnc10.aksw.uni-leipzig.de:8890/sparql'  doesn't seem to work

### ISSUE THREAD

**Issue by JasmineChen123** [dice-group/THOTH#1]
I tried many times to connect to the server but failed. Is the IP address only avaliable in Germany but can not work in other contries? Or it is because the sparql service was shut down previously. If So, how can I get access to the dataset of the experiment?
Hope that you can offer some help to me. Thanks very much.

**Comment by JasmineChen123** [comment]
Thanks a lot. I finally solved this problem.

**Comment by mommi84** [comment]
Unfortunately, that address is no longer available.

The endpoint contained data from DBpedia 2016-10 chapters (`en`, `de`, `it`, `pt`), which can be found here:
- http://downloads.dbpedia.org/2016-10/core-i18n/en/infobox_properties_en.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/de/infobox_properties_de.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/it/infobox_properties_it.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/pt/infobox_properties_pt.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/en/mappingbased_objects_en.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/de/mappingbased_objects_de.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/it/mappingbased_objects_it.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/pt/mappingbased_objects_pt.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/en/interlanguage_links_en.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/de/interlanguage_links_de.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/it/interlanguage_links_it.ttl.bz2
- http://downloads.dbpedia.org/2016-10/core-i18n/pt/interlanguage_links_pt.ttl.bz2

The updated data can be found at:
- https://databus.dbpedia.org/dbpedia/generic/infobox-properties/
- https://databus.dbpedia.org/dbpedia/mappings/mappingbased-objects/
- https://databus.dbpedia.org/dbpedia/generic/interlanguage-links/

To select the right language chapters, replace `lv` with the desired ones:

<img src='https://forum.dbpedia.org/uploads/default/original/1X/940bd307db41055f632abe588b015db428a5c017.gif'>
